version: 0.2

phases:
  build:
    commands:
      - echo Build started on 'webapp'
      - cat /etc/os-release
      - chmod +x install_ps.sh
      - ./install_ps.sh
      - pwsh -command 'get-content buildspec.yml'
      - pwsh -file ./build.ps1
      - docker build -t webapp -f ./webapp/publish
      - docker images
artifacts:
  files:
    - .\bin\Debug\netcoreapp1.0\*