version: 0.2

phases:
  build:
    commands:
      - echo Build started on 'webapp'
      - get-content buildspec.yml
      - dotnet restore webapp/webapp.csproj
      - dotnet build webapp/webapp.csproj
artifacts:
  files:
    - .\bin\Debug\netcoreapp1.0\*