version: 0.2

phases:
  build:
    commands:
      - powershell
      - dotnet restore webapp/webapp.csproj
      - dotnet build webapp/webapp.csproj
artifacts:
  files:
    - .\bin\Debug\netcoreapp1.0\*